import '../globals.css'
import { Inter } from 'next/font/google'

import Topbar from '@/components/shared/Topbar'
import AuthProvider from './context/AuthProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Topbar />
          <main className='bg-zinc-100'>
            <section className='max-w-screen-lg mx-auto flex min-h-screen flex-1 flex-col bg-white'>
              <div className=''>
                {children}
              </div>
            </section>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
